### ISSUE TITLE
ERROR  TypeError: Cannot read property 'createClient' of null

### ISSUE THREAD

**Issue by GokulKir** [friyiajr/BLESampleExpo#3] opened 2023-08-30 07:30 UTC
const manager  = new BleManager()i

this error  -   ERROR  TypeError: Cannot read property 'createClient' of null

This error is located at:
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent), js engine: hermes

**Comment by friyiajr** [comment] 2023-09-05 16:51
Duplicate of https://github.com/friyiajr/BLESampleExpo/issues/1

**Closed as completed by friyiajr** 2023-09-05 16:51 UTC
